# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_N90G6lr5tptXqEVfqC8AFvFTaDkadmp
"""

a,b=10,20
print(a+b)
